import {
  IoIosPhotos,
  IoIosPersonAdd,
  IoMdGift,
  IoIosHourglass,
  IoIosColorPalette,
  IoIosTrendingUp,
} from "react-icons/io";

import {
  BsBriefcaseFill,
  BsBuilding,
  BsListUl,
  BsServer,
} from "react-icons/bs";

export const publicNav = [
    {
      icon: BsListUl,
      name: "Categories",
      className: "sidebar__icons__categories",
      // children: selector.category,
      children: [],
      size: 20,
    },
    {
      icon: IoIosTrendingUp,
      name: "Trending",
      className: "sidebar__icons__trending",
      to: "/",
      size: 20,
    },
    {
      icon: IoIosPhotos,
      name: "Bundle",
      className: "sidebar__icons__bundle",
      to: "/",
      size: 20,
    },
    {
      icon: IoIosPersonAdd,
      name: "Follow",
      className: "sidebar__icons__follow",
      to: "/",
      size: 20,
    },
    {
      icon: BsBuilding,
      name: "Sellers",
      className: "sidebar__icons__sellers",
      to: "/",
      size: 20,
    },
    {
      icon: BsBriefcaseFill,
      name: "Brands",
      className: "sidebar__icons__brands",
      to: "/",
      size: 20,
    },
    {
      icon: IoMdGift,
      name: "Gift",
      className: "header__icons__gift",
      to: "/",
      size: 20,
    },
    {
      icon: IoIosHourglass,
      name: "Promo",
      className: "sidebar__icons__promo",
      to: "/",
      size: 20,
    },
    {
      icon: BsServer,
      name: "Upgrade",
      className: "sidebar__icons__addAccount",
      to: "/",
      size: 20,
    },
    {
      icon: IoIosColorPalette,
      name: "Theme",
      className: "sidebar__icons__theme",
      to: "/",
      size: 20,
    },
    // testing icons
    {
      icon: BsBriefcaseFill,
      name: "Brands",
      className: "sidebar__icons__brands",
      to: "/",
      size: 20,
    },
    {
      icon: IoMdGift,
      name: "Gift",
      className: "header__icons__gift",
      to: "/",
      size: 20,
    },
    {
      icon: IoIosHourglass,
      name: "Promo",
      className: "sidebar__icons__promo",
      to: "/",
      size: 20,
    },
    {
      icon: BsServer,
      name: "Upgrade",
      className: "sidebar__icons__addAccount",
      to: "/",
      size: 20,
    },
    {
      icon: IoIosColorPalette,
      name: "Theme",
      className: "sidebar__icons__theme",
      to: "/",
      size: 20,
    },
    {
      icon: BsBriefcaseFill,
      name: "Brands",
      className: "sidebar__icons__brands",
      to: "/",
      size: 20,
    },
    {
      icon: IoMdGift,
      name: "Gift",
      className: "header__icons__gift",
      to: "/",
      size: 20,
    },
    {
      icon: IoIosHourglass,
      name: "Promo",
      className: "sidebar__icons__promo",
      to: "/",
      size: 20,
    },
    {
      icon: BsServer,
      name: "Upgrade",
      className: "sidebar__icons__addAccount",
      to: "/",
      size: 20,
    },
    {
      icon: IoIosColorPalette,
      name: "Theme",
      className: "sidebar__icons__theme",
      to: "/",
      size: 20,
    },
  ];