const authConstants = {
  USER_SIGNIN_REQUEST: "USER_SIGNIN_REQUEST",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAIL: "USER_SIGNIN_FAIL",

  USER_SIGNOUT_REQUEST: "USER_SIGNOUT_REQUEST",
  USER_SIGNOUT_SUCCESS: "USER_SIGNOUT_SUCCESS",
  USER_SIGNOUT_FAIL: "USER_SIGNOUT_FAIL"

};

const registerConstant = {
  USER_SIGNUP_REQUEST: "USER_SIGNUP_REQUEST",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAIL: "USER_SIGNUP_FAIL",
};


 const videoConstant = {
 GET_VIDEO_SUCCESS: "GET_VIDEO_SUCCESS",

};



 const categoryConstants = {
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAIL: "GET_ALL_CATEGORIES_FAIL",


}

 const globalProductConstant = {
  GET_GLOBALPRODUCT_BY_SLUG_REQUEST: "GET_GLOBALPRODUCT_BY_SLUG_REQUEST",
  GET_GLOBALPRODUCT_BY_SLUG_SUCCESS: "GET_GLOBALPRODUCT_BY_SLUG_SUCCESS",
  GET_GLOBALPRODUCT_BY_SLUG_FAIL: "GET_GLOBALPRODUCT_BY_SLUG_FAIL",
  GET_GLOBALSTOREPRODUCTINFO_BY_SLUG_REQUEST: "GET_GLOBALSTOREPRODUCTINFO_BY_SLUG_REQUEST",
  GET_GLOBALSTOREPRODUCTINFO_BY_SLUG_SUCCESS: "GET_GLOBALSTOREPRODUCTINFO_BY_SLUG_SUCCESS",
  GET_GLOBALSTOREPRODUCTINFO_BY_SLUG_FAIL: "GET_GLOBALSTOREPRODUCTINFO_BY_SLUG_FAIL"
}



 const canvas = {
  SELECTED_SELLER_REQUEST: "SELECTED_SELLER_REQUEST",
  SELECTED_SELLER_SUCCESS: "SELECTED_SELLER_SUCCESS",
  SIDEBAR_SWITCH: "SIDEBAR_SWITCH",
  SIDEBAR_REQUEST: "SIDEBAR_REQUEST",
  SIDEMENU_CONTENT_SWITCH: "SIDEMENU_CONTENT_SWITCH",
  SIDEMENU_CONTENT_REQUEST: "SIDEMENU_CONTENT_REQUEST",
  MENUDATA_REQUEST: "MENUDATA_REQUEST",
  MENUDATA_SUCCESS: "MENUDATA_SUCCESS",
  GLOBAL_PRODUCT_CANVAS_REQUEST: "GLOBAL_PRODUCT_CANVAS_REQUEST",
  GLOBAL_PRODUCT_CANVAS_SUCCESS: "GLOBAL_PRODUCT_CANVAS_SUCCESS",
  GLOBAL_PRODUCT_CANVAS_FAIL: "GLOBAL_PRODUCT_CANVAS_FAIL",

};

export {
  authConstants,
videoConstant,
categoryConstants,
globalProductConstant,
canvas,
registerConstant
}